// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJy3BbajwFw4Fp1msLcDPPOpXiNl-2wPE',
    appId: '1:34009958048:web:151f7da4433cb53cccabc5',
    messagingSenderId: '34009958048',
    projectId: 'factol-2c765',
    authDomain: 'factol-2c765.firebaseapp.com',
    storageBucket: 'factol-2c765.firebasestorage.app',
    measurementId: 'G-V2R9NCZVMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXDv03HhnbojLLtNvf-MPmthZdhozSDFY',
    appId: '1:34009958048:android:046680d148390c1dccabc5',
    messagingSenderId: '34009958048',
    projectId: 'factol-2c765',
    storageBucket: 'factol-2c765.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiMxlNIrTwi-kxsoeHnJxq8Ge1irUyGvs',
    appId: '1:34009958048:ios:847bd2f4856c1f61ccabc5',
    messagingSenderId: '34009958048',
    projectId: 'factol-2c765',
    storageBucket: 'factol-2c765.firebasestorage.app',
    iosBundleId: 'com.example.factolapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiMxlNIrTwi-kxsoeHnJxq8Ge1irUyGvs',
    appId: '1:34009958048:ios:847bd2f4856c1f61ccabc5',
    messagingSenderId: '34009958048',
    projectId: 'factol-2c765',
    storageBucket: 'factol-2c765.firebasestorage.app',
    iosBundleId: 'com.example.factolapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJy3BbajwFw4Fp1msLcDPPOpXiNl-2wPE',
    appId: '1:34009958048:web:9eb5edd7da3fcbd9ccabc5',
    messagingSenderId: '34009958048',
    projectId: 'factol-2c765',
    authDomain: 'factol-2c765.firebaseapp.com',
    storageBucket: 'factol-2c765.firebasestorage.app',
    measurementId: 'G-QFCF073Z7Z',
  );
}
